App\Domain\Entity\Action:
    type: entity
    table: action
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
    manyToOne:
        thing:
            targetEntity: App\Domain\Entity\Thing
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: actions
            joinColumns:
                thing_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        friends:
            targetEntity: App\Domain\Entity\Friend
            cascade: {  }
            fetch: LAZY
            mappedBy: actions
            inversedBy: null
            joinTable: {  }
            orderBy: null
    lifecycleCallbacks: {  }
