-- MySQL Script generated by MySQL Workbench
-- jue 31 ene 2019 11:17:00 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`owner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`owner` ;

CREATE TABLE IF NOT EXISTS `mydb`.`owner` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fbDelegated` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`thing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`thing` ;

CREATE TABLE IF NOT EXISTS `mydb`.`thing` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `root` VARCHAR(45) NULL,
  `user` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`owner_has_thing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`owner_has_thing` ;

CREATE TABLE IF NOT EXISTS `mydb`.`owner_has_thing` (
  `id` VARCHAR(45) NOT NULL,
  `owner_id` INT NOT NULL,
  `thing_id` INT NOT NULL,
  PRIMARY KEY (`id`, `owner_id`, `thing_id`),
  INDEX `fk_owner_has_wt_wt1_idx` (`thing_id` ASC),
  INDEX `fk_owner_has_wt_owner_idx` (`owner_id` ASC),
  CONSTRAINT `fk_owner_has_wt_owner`
    FOREIGN KEY (`owner_id`)
    REFERENCES `mydb`.`owner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_owner_has_wt_wt1`
    FOREIGN KEY (`thing_id`)
    REFERENCES `mydb`.`thing` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`friend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`friend` ;

CREATE TABLE IF NOT EXISTS `mydb`.`friend` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fbDelegated` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`owner_has_friend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`owner_has_friend` ;

CREATE TABLE IF NOT EXISTS `mydb`.`owner_has_friend` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner_id` INT NOT NULL,
  `friend_id` INT NOT NULL,
  INDEX `fk_owner_has_friend_friend1_idx` (`friend_id` ASC),
  INDEX `fk_owner_has_friend_owner1_idx` (`owner_id` ASC),
  PRIMARY KEY (`id`, `owner_id`, `friend_id`),
  CONSTRAINT `fk_owner_has_friend_owner1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `mydb`.`owner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_owner_has_friend_friend1`
    FOREIGN KEY (`friend_id`)
    REFERENCES `mydb`.`friend` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`action`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`action` ;

CREATE TABLE IF NOT EXISTS `mydb`.`action` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `wt_id` INT NOT NULL,
  `http_verb` INT NOT NULL,
  `route` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `wt_id`, `http_verb`),
  INDEX `fk_table1_wt1_idx` (`wt_id` ASC),
  CONSTRAINT `fk_table1_wt1`
    FOREIGN KEY (`wt_id`)
    REFERENCES `mydb`.`thing` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`friend_has_action`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`friend_has_action` ;

CREATE TABLE IF NOT EXISTS `mydb`.`friend_has_action` (
  `friend_id` INT NOT NULL,
  `action_id` INT NOT NULL,
  `action_wt_id` INT NOT NULL,
  PRIMARY KEY (`friend_id`, `action_id`, `action_wt_id`),
  INDEX `fk_friend_has_action_action1_idx` (`action_id` ASC, `action_wt_id` ASC),
  INDEX `fk_friend_has_action_friend1_idx` (`friend_id` ASC),
  CONSTRAINT `fk_friend_has_action_friend1`
    FOREIGN KEY (`friend_id`)
    REFERENCES `mydb`.`friend` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friend_has_action_action1`
    FOREIGN KEY (`action_id` , `action_wt_id`)
    REFERENCES `mydb`.`action` (`id` , `wt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
