# TODO: remove this test route (front development purpose only)
test:
    path: /test
    controller: App\Infrastructure\Controllers\CredentialsController::test

handlebars:
    path: /handlebars
    controller: App\Infrastructure\Controllers\CredentialsController::handlebars


#    TODO: use @App notation, (but bundle must be "correctly registered and loaded in the application kernel class"
credential_routes:
    resource: '../src/Infrastructure/Resources/config/routes/credentials.yaml'

owner_routes:
    resource: '../src/Infrastructure/Resources/config/routes/owner.yaml'

thing_routes:
    resource: '../src/Infrastructure/Resources/config/routes/thing.yaml'

friend_routes:
    resource: '../src/Infrastructure/Resources/config/routes/friend.yaml'

api_routes:
    resource: '../src/Infrastructure/Resources/config/routes/api.yaml'

error_routes:
    resource: '../src/Infrastructure/Resources/config/routes/error.yaml'

success_routes:
    resource: '../src/Infrastructure/Resources/config/routes/success.yaml'
