test:
    path: /test
    controller: App\Infrastructure\CredentialsController::test


#    TODO: use @App notation, (but bundle must be "correctly registered and loaded in the application kernel class"
credential_routes:
    resource: '../src/Infrastructure/Routes/credentials.yaml'
owner_routes:
    resource: '../src/Infrastructure/Routes/owner.yaml'

thing_routes:
    resource: '../src/Infrastructure/Routes/thing.yaml'


