# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  # TODO borrar esta línea si no se usa en constructor de CurlThingConnectedRepository
  endpoint: 'localhost'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.



  event_subscribers:
    namespace: App\Infrastructure\EventSubscriber\
    resource: '../src/Infrastructure/EventSubscriber'
    tags: [event_subscriber]

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  app.repository.owner:
    class: App\Infrastructure\Owner\MySQLOwnerRepository
    public: true
    arguments:
    - "@doctrine.orm.default_entity_manager"

  app.command_handler.owner.create:
    class: App\Application\CommandHandler\Owner\CreateOwnerHandler
    public: true
    arguments:
    - "@app.repository.owner"

  app.command_handler.owner.search.by_fb_delegated:
    class: App\Application\CommandHandler\Owner\SearchOwnerByFbDelegatedHandler
    public: true
    arguments:
    - "@app.repository.owner"

  app.command_handler.owner.get_fb_sharing_status.by_owner:
    class: App\Application\CommandHandler\Owner\GetFbSharingStatusByOwnerHandler
    public: true
    arguments:
    - "@app.repository.owner"

# TODO try this
  app.command_handler.owner.add_friend:
    class: App\Application\CommandHandler\Owner\AddFriendToOwner
    public: true
    arguments:
    - "@app.repository.owner"

# TODO test this
  app.command_handler.owner.add_thing:
    class: App\Application\CommandHandler\Owner\AddThingToOwnerHandler
    public: true
    arguments:
    - "@app.repository.owner"


# THING
  app.repository.thing:
    class: App\Infrastructure\Thing\MySQLThingRepository
    public: true
    arguments:
    - "@doctrine.orm.default_entity_manager"

# TODO test this
  app.command_handler.thing.search_by_id:
    class: App\Application\CommandHandler\Thing\SearchThingByIdHandler
    public: true
    arguments:
    - "@app.repository.thing"

  # TODO test this
  app.command_handler.thing.get_actions:
    class: App\Application\CommandHandler\Thing\GetActionsByThingIdHandler
    public: true
    arguments:
    - "@app.repository.thing"

  app.command_handler.thing.merge_thing_with_thing_connected:
    class: App\Application\CommandHandler\Thing\MergeThingWithThingConnectedByIdHandler
    public: true
    arguments:
    - "@app.command_handler.thing.search_by_id"
    - "@app.command_handler.thing_connected.get_complete"

# THINGCONNECTED
  app.repository.thing_connected:
    class: App\Infrastructure\ThingConnected\CurlThingConnectedRepository
    public: true
#    arguments:
#      $endpoint: "localhost"
#       $port: 8001
#

  app.command_handler.thing_connected.get_actions:
    class: App\Application\CommandHandler\Thing\ThingConnected\GetThingConnectedActionsHandler
    public: true
    arguments:
    - "@app.repository.thing_connected"

  app.command_handler.thing_connected.get_complete:
    class: App\Application\CommandHandler\Thing\ThingConnected\GetThingConnectedCompleteHandler
    public: true
    arguments:
    - "@app.repository.thing_connected"

# TODO faltan de ThingConnected get_name, get_brand






# FRIEND
  app.repository.friend:
    class: App\Infrastructure\Friend\MySQLFriendRepository
    public: true
    arguments:
    - "@doctrine.orm.default_entity_manager"

# ACTION
  app.repository.action:
    class: App\Infrastructure\Action\MySQLActionRepository
    public: true
    arguments:
    - "@doctrine.orm.default_entity_manager"


