api_owner:
  path: /api/owner
#  path: /api/owner/{fbDelegated}
  controller: App\Infrastructure\Controllers\Api\OwnerApiController::info
  methods: [GET]

api_thing:
  path: /api/thing/{thingId}
  controller: App\Infrastructure\Controllers\Api\ThingApiController::info
  methods: [GET]
