api_owner:
  path: /api/owner
  controller: App\Infrastructure\Controllers\Api\OwnerApiController::info
  methods: [GET]

api_thing:
  path: /api/thing/{thingId}
  controller: App\Infrastructure\Controllers\Api\ThingApiController::info
  methods: [GET]

api_share_action:
  path: /owner/share/action/{actionId}/friend/{friendId}
  controller: App\Infrastructure\Controllers\Api\OwnerApiController::shareActionWithFriend
  requirements:
    friendId: '\d+'
    actionId: '\d+'
  methods: [GET]

url_provider_for_thing_info:
  path: /api/url/provider/thing
  controller: App\Infrastructure\Controllers\Api\ApiUrlGeneratorController::urlForThingInfoProvider
  requirements:
    thingId: '\d+'
  methods: [GET]