api_owner:
  path: /api/owner
  controller: App\Infrastructure\Controllers\Api\Owner\Owner::info

owner_get_things:
  path: /api/owner/get_things
  controller: App\Infrastructure\Controllers\Api\Owner\Owner::getListThings