login:
  path: /
  controller: App\Infrastructure\Controllers\CredentialsController::login

# TODO: duda, esta se usa?
loginOk:
  path: /loginOk
  controller: App\Infrastructure\Controllers\CredentialsController::loginOk

# TODO: duda, esta se usa?
loginStatus:
  path: /loginStatus
  controller: App\Infrastructure\Controllers\CredentialsController::loginStatus

privacy:
  path: /privacy
  controller: App\Infrastructure\Controllers\CredentialsController::privacy

conditions:
  path: /conditions
  controller: App\Infrastructure\Controllers\CredentialsController::conditions
